# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/g/My Drive/2021-2022/2022Spring/CS170/project/project1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/g/My Drive/2021-2022/2022Spring/CS170/project/project1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/g/My Drive/2021-2022/2022Spring/CS170/project/project1/CMakeFiles" "/mnt/g/My Drive/2021-2022/2022Spring/CS170/project/project1/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/g/My Drive/2021-2022/2022Spring/CS170/project/project1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main.out

# Build rule for target.
main.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main.out
.PHONY : main.out

# fast build rule for target.
main.out/fast:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/build
.PHONY : main.out/fast

#=============================================================================
# Target rules for targets named test.out

# Build rule for target.
test.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test.out
.PHONY : test.out

# fast build rule for target.
test.out/fast:
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/build
.PHONY : test.out/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/main.cpp.s
.PHONY : main.cpp.s

src/AStar.o: src/AStar.cpp.o

.PHONY : src/AStar.o

# target to build an object file
src/AStar.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/AStar.cpp.o
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/AStar.cpp.o
.PHONY : src/AStar.cpp.o

src/AStar.i: src/AStar.cpp.i

.PHONY : src/AStar.i

# target to preprocess a source file
src/AStar.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/AStar.cpp.i
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/AStar.cpp.i
.PHONY : src/AStar.cpp.i

src/AStar.s: src/AStar.cpp.s

.PHONY : src/AStar.s

# target to generate assembly for a file
src/AStar.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/AStar.cpp.s
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/AStar.cpp.s
.PHONY : src/AStar.cpp.s

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Board.cpp.o
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Board.cpp.i
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Board.cpp.s
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Problem.o: src/Problem.cpp.o

.PHONY : src/Problem.o

# target to build an object file
src/Problem.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Problem.cpp.o
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Problem.cpp.o
.PHONY : src/Problem.cpp.o

src/Problem.i: src/Problem.cpp.i

.PHONY : src/Problem.i

# target to preprocess a source file
src/Problem.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Problem.cpp.i
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Problem.cpp.i
.PHONY : src/Problem.cpp.i

src/Problem.s: src/Problem.cpp.s

.PHONY : src/Problem.s

# target to generate assembly for a file
src/Problem.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Problem.cpp.s
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Problem.cpp.s
.PHONY : src/Problem.cpp.s

src/Tree.o: src/Tree.cpp.o

.PHONY : src/Tree.o

# target to build an object file
src/Tree.cpp.o:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Tree.cpp.o
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Tree.cpp.o
.PHONY : src/Tree.cpp.o

src/Tree.i: src/Tree.cpp.i

.PHONY : src/Tree.i

# target to preprocess a source file
src/Tree.cpp.i:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Tree.cpp.i
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Tree.cpp.i
.PHONY : src/Tree.cpp.i

src/Tree.s: src/Tree.cpp.s

.PHONY : src/Tree.s

# target to generate assembly for a file
src/Tree.cpp.s:
	$(MAKE) -f CMakeFiles/main.out.dir/build.make CMakeFiles/main.out.dir/src/Tree.cpp.s
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/src/Tree.cpp.s
.PHONY : src/Tree.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main.out"
	@echo "... test.out"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/AStar.o"
	@echo "... src/AStar.i"
	@echo "... src/AStar.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Problem.o"
	@echo "... src/Problem.i"
	@echo "... src/Problem.s"
	@echo "... src/Tree.o"
	@echo "... src/Tree.i"
	@echo "... src/Tree.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

